// data.jsx — seed data and constants

const TIERS = [
  {
    id: "trial",
    name: "Trial",
    nameTh: "ทดลองใช้",
    price: 0,
    priceLabel: "ฟรี 30 วัน",
    chatQuota: 30,
    chatLabel: "30 ครั้ง / เดือน",
    period: "30 วันแรก",
    perks: [
      "เข้าถึงข้อมูลงานประมูลครบ",
      "ตั้ง Business Class ได้ไม่จำกัด",
      "Sebastian Chat 30 ครั้ง / เดือน",
      "แจ้งเตือนงานประจำวัน",
    ],
    note: "เริ่มต้นสำหรับท่านที่ยังไม่เคยใช้บริการ",
  },
  {
    id: "starter",
    name: "Starter",
    nameTh: "เริ่มต้น",
    price: 1500,
    priceLabel: "1,500 ฿/เดือน",
    chatQuota: 15,
    chatLabel: "15 ครั้ง / เดือน",
    perks: [
      "เข้าถึงข้อมูลงานประมูลครบ",
      "Sebastian Chat 15 ครั้ง / เดือน",
      "แจ้งเตือนงานทุกเช้า",
      "รองรับหลาย Business Class",
    ],
    note: "เหมาะกับท่านที่ใช้แชทไม่บ่อย",
  },
  {
    id: "standard",
    name: "Standard",
    nameTh: "มาตรฐาน",
    price: 1800,
    priceLabel: "1,800 ฿/เดือน",
    chatQuota: 30,
    chatLabel: "30 ครั้ง / เดือน",
    perks: [
      "ทุกอย่างใน Starter",
      "Sebastian Chat 30 ครั้ง / เดือน",
      "วิเคราะห์งานคู่แข่งเบื้องต้น",
    ],
    note: "ขายดี — สมดุลระหว่างราคาและความสามารถ",
    popular: true,
  },
  {
    id: "premium",
    name: "Premium",
    nameTh: "พรีเมียม",
    price: 2100,
    priceLabel: "2,100 ฿/เดือน",
    chatQuota: -1,
    chatLabel: "ไม่จำกัด",
    perks: [
      "ทุกอย่างใน Standard",
      "Sebastian Chat ไม่จำกัด",
      "อ่าน/สรุปเอกสารประมูล",
      "วิเคราะห์คู่แข่งเชิงลึก",
    ],
    note: "สำหรับท่านที่ต้องการคุยกับ Sebastian ตลอดเวลา",
  },
  {
    id: "ultra",
    name: "Ultra Luxury",
    nameTh: "อัลตร้า ลักชัวรี่",
    price: 3500,
    priceLabel: "3,500 ฿/เดือน",
    chatQuota: -1,
    chatLabel: "ไม่จำกัด",
    perks: [
      "ทุกอย่างใน Premium",
      "วิเคราะห์งานหลายงานพร้อมกัน",
      "สร้าง Dashboard สรุปได้",
      "Sebastian จัดเอกสารให้อัตโนมัติ",
      "Priority support 24 ชม.",
    ],
    note: "บริการเต็มรูปแบบ ราวกับมีพ่อบ้านส่วนตัว",
  },
];

const PROVINCES = PROVINCES_FULL; // re-export full 77-province list from thai-admin.jsx

const SEED_CLASSES = [
  {
    id: "c1",
    name: "คอนกรีตผสมเสร็จ",
    icon: "concrete",
    color: "#C8A86A",
    geo: {
      mode: "both",
      provinces: ["กรุงเทพมหานคร", "นนทบุรี", "ปทุมธานี", "สมุทรปราการ"],
      districts: ["กรุงเทพมหานคร::บางบอน", "กรุงเทพมหานคร::บางขุนเทียน"],
      tambons: [],
      gps: { lat: 13.6843, lng: 100.4129, label: "โรงงานบางบอน 4" },
      radiusKm: 35,
    },
    keywords: ["คอนกรีตผสมเสร็จ", "Ready-mixed Concrete", "RMC", "CPAC", "TPI", "INSEE"],
    defaultKeywords: ["คอนกรีตผสมเสร็จ", "Ready-mixed Concrete", "RMC"],
  },
  {
    id: "c2",
    name: "ท่ออัดแรง",
    icon: "pipe",
    color: "#8B2A36",
    geo: {
      mode: "province",
      provinces: ["กรุงเทพมหานคร", "นนทบุรี", "ปทุมธานี", "สมุทรปราการ", "สมุทรสาคร", "นครปฐม"],
      districts: [],
      tambons: [],
      gps: null,
      radiusKm: 0,
    },
    keywords: ["ท่ออัดแรง", "ท่อคอนกรีตอัดแรง", "Prestressed Concrete Pipe", "PC Pipe"],
    defaultKeywords: ["ท่ออัดแรง", "ท่อคอนกรีตอัดแรง"],
  },
  {
    id: "c3",
    name: "รับเหมาก่อสร้างทั่วไป",
    icon: "build",
    color: "#4A7C59",
    geo: {
      mode: "radius",
      provinces: [],
      districts: [],
      tambons: [],
      gps: { lat: 13.7563, lng: 100.5018, label: "สำนักงานใหญ่ พระราม 4" },
      radiusKm: 80,
    },
    keywords: ["รับเหมาก่อสร้าง", "ก่อสร้างอาคาร", "งานโยธา", "ปรับปรุงอาคาร"],
    defaultKeywords: ["รับเหมาก่อสร้าง", "ก่อสร้างอาคาร", "งานโยธา"],
  },
];

const SEED_PROFILE = {
  companyName: "บริษัท ราชสีห์คอนสตรัคชั่น จำกัด",
  phone: "02-555-1234",
  email: "info@rajasee.co.th",
  budgetMin: 1, // million THB
  budgetMax: 50,
  isSME: true,
  isMIT: true,
  notifyTime: "06:00",
};

const SEED_JOBS = [
  {
    id: "j1",
    stage: "bidding",
    title: "ก่อสร้างปรับปรุงถนนคอนกรีต ซอยเทศบาล 4",
    agency: "เทศบาลตำบลบางบ่อ จ.สมุทรปราการ",
    budget: 8.5,
    deadline: "2026-05-28",
    daysLeft: 9,
    matchedClass: "c1",
    matchedKeywords: ["คอนกรีตผสมเสร็จ", "RMC"],
    distance: 12,
    sme: true, mit: true,
  },
  {
    id: "j2",
    stage: "bidding",
    title: "จ้างเหมาก่อสร้างระบบระบายน้ำ ท่ออัดแรง",
    agency: "อบจ.นครปฐม",
    budget: 24.2,
    deadline: "2026-06-04",
    daysLeft: 16,
    matchedClass: "c2",
    matchedKeywords: ["ท่ออัดแรง", "ท่อคอนกรีตอัดแรง"],
    distance: 48,
    sme: true, mit: true,
  },
  {
    id: "j3",
    stage: "bidding",
    title: "ปรับปรุงอาคารสำนักงาน 3 ชั้น",
    agency: "ศาลากลางจังหวัดนนทบุรี",
    budget: 14.0,
    deadline: "2026-05-23",
    daysLeft: 4,
    matchedClass: "c3",
    matchedKeywords: ["รับเหมาก่อสร้าง", "ปรับปรุงอาคาร"],
    distance: 22,
    sme: false, mit: true,
  },
  {
    id: "j4",
    stage: "bidding",
    title: "ก่อสร้างพื้นคอนกรีตลานจอดรถ 4,200 ตร.ม.",
    agency: "การประปาส่วนภูมิภาค สาขาปทุมธานี",
    budget: 6.8,
    deadline: "2026-05-31",
    daysLeft: 12,
    matchedClass: "c1",
    matchedKeywords: ["คอนกรีตผสมเสร็จ"],
    distance: 28,
    sme: true, mit: true,
  },
  {
    id: "j5",
    stage: "bidding",
    title: "วางท่อระบายน้ำ ถ.ราชพฤกษ์ ขยาย 4 ช่อง",
    agency: "กรมทางหลวงชนบท",
    budget: 32.5,
    deadline: "2026-06-12",
    daysLeft: 24,
    matchedClass: "c2",
    matchedKeywords: ["ท่ออัดแรง", "PC Pipe"],
    distance: 18,
    sme: true, mit: true,
  },

  /* Pre-TOR: ร่าง TOR เผยแพร่เพื่อรับฟังความคิดเห็น ก่อนประกาศประมูลจริง */
  {
    id: "p1",
    stage: "pretor",
    title: "ก่อสร้างถนนคอนกรีตเสริมเหล็ก สายบ้านโคก-บ้านดอน",
    agency: "อบต.บางพลีน้อย จ.สมุทรปราการ",
    budget: 11.2,
    pretorPhase: "รับฟังความเห็น",
    pretorEnd: "2026-05-26",
    daysToComment: 7,
    expectedBidDate: "มิ.ย. 2026",
    matchedClass: "c1",
    matchedKeywords: ["คอนกรีตผสมเสร็จ", "ถนนคอนกรีต"],
    distance: 22,
    sme: true, mit: true,
  },
  {
    id: "p2",
    stage: "pretor",
    title: "ก่อสร้างระบบระบายน้ำพร้อมท่อคอนกรีตอัดแรง ระยะที่ 2",
    agency: "เทศบาลนครนนทบุรี",
    budget: 45.8,
    pretorPhase: "ร่าง TOR ครั้งที่ 1",
    pretorEnd: "2026-05-30",
    daysToComment: 11,
    expectedBidDate: "ปลายมิ.ย. 2026",
    matchedClass: "c2",
    matchedKeywords: ["ท่อคอนกรีตอัดแรง", "ท่ออัดแรง"],
    distance: 35,
    sme: true, mit: true,
  },
  {
    id: "p3",
    stage: "pretor",
    title: "ปรับปรุงอาคารศูนย์ราชการ ระยะที่ 3",
    agency: "กรมโยธาธิการและผังเมือง",
    budget: 28.0,
    pretorPhase: "ร่าง TOR ครั้งที่ 2",
    pretorEnd: "2026-06-02",
    daysToComment: 14,
    expectedBidDate: "ก.ค. 2026",
    matchedClass: "c3",
    matchedKeywords: ["รับเหมาก่อสร้าง", "ปรับปรุงอาคาร"],
    distance: 8,
    sme: false, mit: true,
  },
];

const DEFAULT_KEYWORDS_BY_CLASS = {
  "คอนกรีตผสมเสร็จ": ["คอนกรีตผสมเสร็จ", "Ready-mixed Concrete", "RMC"],
  "ท่ออัดแรง": ["ท่ออัดแรง", "ท่อคอนกรีตอัดแรง", "Prestressed Concrete Pipe"],
  "รับเหมาก่อสร้าง": ["รับเหมาก่อสร้าง", "ก่อสร้างอาคาร", "งานโยธา"],
  "งานโยธา": ["งานโยธา", "ก่อสร้างถนน", "ท่อระบายน้ำ"],
};

Object.assign(window, {
  TIERS, PROVINCES, SEED_CLASSES, SEED_PROFILE, SEED_JOBS, DEFAULT_KEYWORDS_BY_CLASS,
});
